* choose different;
filename liverdat url 'http://www.stat.purdue.edu/~wsharaba/stat512/LiverSteatosis.csv';
*read in data;
data liver;
	*specify comma as delimiter, set infile to begin reading at second row;
	infile liverdat delimiter=',' dsd firstobs=2;
	input Age Sex Height Weight BMI Obes DM Met HTN HPL TG CHOL HDL LDL VDL AST ALT NAS Fibrosis LS_US LS_Bi;
	data liver; set liver;
	*for Box-Cox, response variable can't be zero. I add small number to all responses so that they are non-zero;
	LS_Bi_adj=LS_Bi+0.001;
	*Update x for the response variable that you want to investigate. It will update the variable in all subsequent procedures. the xT and yT variables let you transform based on the box-cox results;
	x=LS_US;
	xT=sqrt(x);
	y=LS_Bi_adj;
	yT=sqrt(y);
	*plot data and see if it looks like it needs to be transformed e.g. is there a non-linear relationship between x and y;
	proc sort data=liver; by x;
	proc gplot data=liver;
	plot y*x;
	title1 'Plot of explanatory variable vs. LS_Bi_Adj, no transformation';
	*plot residuals vs explanatory variable and look for constant residuals;
	proc reg data=liver;
	model y=x;
	output out=notrans r=resid;
proc gplot data=notrans;
plot resid*x/vref=0;
title1 'Residual vs. explanatory variable plot,no transformation';
*make qqplot of residuals and look for normality;
proc univariate data=notrans;
var resid; qqplot/normal (L=1 mu=est sigma=est);
	run;
*run box-cox procedure and find optimal lambda value;
proc transreg data=liver;
  model boxcox(y)=identity(x);
  run;
  *look at box-cox plot and figure out what transformation should be used, then transform the variable. Transformation is done in the data step above;
  proc reg data=liver;
	model y=xT;
	title1 'Transformed';
	output out=notrans r=resid;
proc gplot data=notrans;
plot resid*xT/vref=0;
title1 'Residual vs. explanatory variable plot,transformed';
proc univariate data=notrans;
var resid; qqplot/normal (L=1 mu=est sigma=est);
	run;
quit;
